---
name: Lint

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout 5m --verbose

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19

  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "."
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy:
                check-keys: false
